module.exports={
    images:{
        domains:[
            "links.paparreact.com",
            "platform-lookside.fbsbx.com",
            "firebasestorage.googleapis.com",
            "https://play-lh.googleusercontent.com"
            ],
        },
    };